name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Desabilita clone superficial para análise completa

      # Etapa para compilar o projeto Java
      - name: Build with Maven
        run: mvn clean install  # Substituir por 'gradle build' se for um projeto Gradle

      # Etapa de análise do SonarCloud
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Para obter informações de PR
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
